"""add xendit invoice fields to transactions

Revision ID: b098ab915d45
Revises: 0001
Create Date: 2026-06-26 08:06:18.792422+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b098ab915d45'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.drop_constraint('uq_bookings_booking_code', 'bookings', type_='unique')
    op.drop_index('ix_bookings_booking_code', table_name='bookings')
    op.create_index(op.f('ix_bookings_booking_code'), 'bookings', ['booking_code'], unique=True)
    op.drop_index('ix_disbursement_items_disbursement_id', table_name='commission_disbursement_items')
    op.drop_index('ix_disbursement_items_transaction_id', table_name='commission_disbursement_items')
    op.create_index(op.f('ix_commission_disbursement_items_disbursement_id'), 'commission_disbursement_items', ['disbursement_id'], unique=False)
    op.create_index(op.f('ix_commission_disbursement_items_transaction_id'), 'commission_disbursement_items', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_commission_disbursements_id'), 'commission_disbursements', ['id'], unique=False)
    op.create_index(op.f('ix_destinations_vendor_id'), 'destinations', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_guide_withdrawals_id'), 'guide_withdrawals', ['id'], unique=False)
    op.alter_column('guides', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('transactions', sa.Column('xendit_invoice_url', sa.Text(), nullable=True))
    op.alter_column('transactions', 'transaction_code',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('transactions', 'gross_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'IDR'::character varying"))
    op.alter_column('transactions', 'receipt_image',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('transactions', 'split_config_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('transactions', 'vendor_percent_snapshot',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'guide_percent_snapshot',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'platform_percent_snapshot',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'vendor_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('transactions', 'guide_commission',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('transactions', 'platform_fee',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.alter_column('transactions', 'payment_method',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('transactions', 'xendit_invoice_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('transactions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_transactions_guide_id', table_name='transactions')
    op.drop_index('ix_transactions_id', table_name='transactions')
    op.drop_index('ix_transactions_vendor_id', table_name='transactions')
    op.drop_constraint('uq_transactions_booking_id', 'transactions', type_='unique')
    op.drop_constraint('uq_transactions_transaction_code', 'transactions', type_='unique')
    op.drop_index('ix_transactions_transaction_code', table_name='transactions')
    op.create_index(op.f('ix_transactions_transaction_code'), 'transactions', ['transaction_code'], unique=True)
    op.create_index(op.f('ix_transactions_xendit_invoice_id'), 'transactions', ['xendit_invoice_id'], unique=False)
    op.drop_constraint('fk_transactions_vendor_id', 'transactions', type_='foreignkey')
    op.drop_constraint('fk_transactions_split_config_id', 'transactions', type_='foreignkey')
    op.drop_constraint('fk_transactions_booking_id', 'transactions', type_='foreignkey')
    op.drop_constraint('fk_transactions_guide_id', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'guides', ['guide_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'revenue_split_configs', ['split_config_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'bookings', ['booking_id'], ['id'])
    op.drop_column('transactions', 'xendit_payment_id')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.create_index(op.f('ix_users_user_email'), 'users', ['user_email'], unique=True)
    op.create_index(op.f('ix_vendor_deposit_topups_id'), 'vendor_deposit_topups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_deposit_topups_id'), table_name='vendor_deposit_topups')
    op.drop_index(op.f('ix_users_user_email'), table_name='users')
    op.create_unique_constraint('uq_users_email', 'users', ['user_email'])
    op.create_index('ix_users_email', 'users', ['user_email'], unique=False)
    op.add_column('transactions', sa.Column('xendit_payment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('fk_transactions_guide_id', 'transactions', 'guides', ['guide_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_transactions_booking_id', 'transactions', 'bookings', ['booking_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_transactions_split_config_id', 'transactions', 'revenue_split_configs', ['split_config_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_transactions_vendor_id', 'transactions', 'vendors', ['vendor_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_transactions_xendit_invoice_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_code'), table_name='transactions')
    op.create_index('ix_transactions_transaction_code', 'transactions', ['transaction_code'], unique=False)
    op.create_unique_constraint('uq_transactions_transaction_code', 'transactions', ['transaction_code'])
    op.create_unique_constraint('uq_transactions_booking_id', 'transactions', ['booking_id'])
    op.create_index('ix_transactions_vendor_id', 'transactions', ['vendor_id'], unique=False)
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    op.create_index('ix_transactions_guide_id', 'transactions', ['guide_id'], unique=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'xendit_invoice_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('transactions', 'payment_method',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('transactions', 'platform_fee',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('transactions', 'guide_commission',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('transactions', 'vendor_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('transactions', 'platform_percent_snapshot',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('transactions', 'guide_percent_snapshot',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('transactions', 'vendor_percent_snapshot',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('transactions', 'split_config_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('transactions', 'receipt_image',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('transactions', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'IDR'::character varying"))
    op.alter_column('transactions', 'gross_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'transaction_code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('transactions', 'xendit_invoice_url')
    op.alter_column('guides', 'bio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_guide_withdrawals_id'), table_name='guide_withdrawals')
    op.drop_index(op.f('ix_destinations_vendor_id'), table_name='destinations')
    op.drop_index(op.f('ix_commission_disbursements_id'), table_name='commission_disbursements')
    op.drop_index(op.f('ix_commission_disbursement_items_transaction_id'), table_name='commission_disbursement_items')
    op.drop_index(op.f('ix_commission_disbursement_items_disbursement_id'), table_name='commission_disbursement_items')
    op.create_index('ix_disbursement_items_transaction_id', 'commission_disbursement_items', ['transaction_id'], unique=False)
    op.create_index('ix_disbursement_items_disbursement_id', 'commission_disbursement_items', ['disbursement_id'], unique=False)
    op.drop_index(op.f('ix_bookings_booking_code'), table_name='bookings')
    op.create_index('ix_bookings_booking_code', 'bookings', ['booking_code'], unique=False)
    op.create_unique_constraint('uq_bookings_booking_code', 'bookings', ['booking_code'])
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    # ### end Alembic commands ###
