"""add_packages

Revision ID: 33ca01a9f9fd
Revises: 0002
Create Date: 2026-06-26 13:57:36.670796+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33ca01a9f9fd'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_per_pax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_pax', sa.Integer(), nullable=False),
    sa.Column('max_pax', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('available_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('available_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quota_per_slot', sa.Integer(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_index(op.f('ix_packages_vendor_id'), 'packages', ['vendor_id'], unique=False)
    op.add_column('bookings', sa.Column('booking_type', sa.String(length=10), nullable=False))
    op.add_column('bookings', sa.Column('package_id', sa.UUID(), nullable=True))
    op.add_column('bookings', sa.Column('package_price_snapshot', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('subtotal_package', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_by', sa.String(length=10), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_reason', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_bookings_package_id'), 'bookings', ['package_id'], unique=False)
    op.drop_constraint('fk_bookings_product_id', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'packages', ['package_id'], ['id'], ondelete='SET NULL')
    op.drop_column('bookings', 'product_id')
    op.add_column('transactions', sa.Column('extra_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('extra_notes', sa.Text(), nullable=True))
    op.alter_column('transactions', 'gross_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'receipt_image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               nullable=True)
    op.alter_column('transactions', 'vendor_amount',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
    op.alter_column('transactions', 'guide_commission',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
    op.alter_column('transactions', 'platform_fee',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=False)
    op.alter_column('transactions', 'xendit_invoice_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('transactions', 'xendit_invoice_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_transactions_xendit_invoice_id', table_name='transactions')
    op.create_index(op.f('ix_transactions_guide_id'), 'transactions', ['guide_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_vendor_id'), 'transactions', ['vendor_id'], unique=False)
    op.create_unique_constraint(None, 'transactions', ['booking_id'])
    op.drop_constraint('transactions_split_config_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_vendor_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_booking_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_guide_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'bookings', ['booking_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'transactions', 'vendors', ['vendor_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'transactions', 'revenue_split_configs', ['split_config_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'guides', ['guide_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('transactions', 'currency')
    op.drop_column('transactions', 'submitted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'IDR'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_guide_id_fkey', 'transactions', 'guides', ['guide_id'], ['id'])
    op.create_foreign_key('transactions_booking_id_fkey', 'transactions', 'bookings', ['booking_id'], ['id'])
    op.create_foreign_key('transactions_vendor_id_fkey', 'transactions', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key('transactions_split_config_id_fkey', 'transactions', 'revenue_split_configs', ['split_config_id'], ['id'])
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_vendor_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_guide_id'), table_name='transactions')
    op.create_index('ix_transactions_xendit_invoice_id', 'transactions', ['xendit_invoice_id'], unique=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'xendit_invoice_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('transactions', 'xendit_invoice_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('transactions', 'platform_fee',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('transactions', 'guide_commission',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('transactions', 'vendor_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               nullable=True)
    op.alter_column('transactions', 'receipt_image',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('transactions', 'gross_amount',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               existing_nullable=False)
    op.drop_column('transactions', 'extra_notes')
    op.drop_column('transactions', 'extra_amount')
    op.add_column('bookings', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('fk_bookings_product_id', 'bookings', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_bookings_package_id'), table_name='bookings')
    op.drop_column('bookings', 'cancelled_at')
    op.drop_column('bookings', 'cancelled_reason')
    op.drop_column('bookings', 'cancelled_by')
    op.drop_column('bookings', 'subtotal_package')
    op.drop_column('bookings', 'package_price_snapshot')
    op.drop_column('bookings', 'package_id')
    op.drop_column('bookings', 'booking_type')
    op.drop_index(op.f('ix_packages_vendor_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_table('packages')
    # ### end Alembic commands ###
